# Generated by Django 5.0.2 on 2024-04-03 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spotifytoken",
            old_name="access",
            new_name="access_token",
        ),
        migrations.RenameField(
            model_name="spotifytoken",
            old_name="refresh",
            new_name="refresh_token",
        ),
    ]
